- name: Test DB Connectivity
  hosts: db
  gather_facts: no
  tasks:
    - name: Get MySQL version with non-default credentials
      delegate_to: localhost
      community.mysql.mysql_info:
        login_user: root
        login_host: "{{inventory_hostname}}"
        filter: version
