- name: Get DB Version
  hosts: db
  gather_facts: no
  tasks:
    - name: Get MySQL Version
      delegate_to: localhost
      community.mysql.mysql_info:
        login_user: root
        login_host: "{{inventory_hostname}}"
        filter: version
      register: versionInfo
    - name: Version Info
      ansible.builtin.debug:
        msg: "{{ versionInfo.version.full }}"
